"""
LinkedIn Job Search → Gmail Digest
Run with: python3 linkedin_job_search.py
Requires: pip install anthropic
          ANTHROPIC_API_KEY env var set
          Claude Code CLI with Gmail MCP connected
"""

import anthropic
import json
from datetime import date

# ── CONFIG ────────────────────────────────────────────────────────────────────

RECIPIENT_EMAIL = "Ofer.man.om@gmail.com"
LOCATION = "Tel Aviv"
TITLES = [
    "Senior Implementation Engineer",
    "Senior Onboarding Engineer",
    "Senior Technical Account Manager",
    "Senior Technical Consultant",
    "Senior CX Engineer",
    "Senior Consultant",
    "Enablement Team Lead",
    "Senior Enablement Manager",
    "Implementation Manager",
    "Senior Implementation Manager",
]
INDUSTRY_KEYWORDS = '("SaaS" OR "software" OR "high-tech" OR "B2B" OR "cloud" OR "IT management" OR "HR tech")'
TODAY = date.today().strftime("%B %d, %Y")

# ── SEARCH QUERIES ────────────────────────────────────────────────────────────

def build_queries():
    queries = []
    for title in TITLES:
        queries.append(
            f'site:linkedin.com/jobs/view "{title}" "{LOCATION}" {INDUSTRY_KEYWORDS}'
        )
    queries.append(
        f'site:linkedin.com/jobs/view ("Implementation Manager" OR "Enablement Manager" OR "Enablement Lead" '
        f'OR "Senior Onboarding" OR "Senior TAM") "{LOCATION}" {INDUSTRY_KEYWORDS}'
    )
    return queries

# ── PROMPTS ───────────────────────────────────────────────────────────────────

SEARCH_SYSTEM = """You are a job search assistant.
When given a Google search query for LinkedIn jobs, use the web_search tool to run it.
Extract ALL job results found and return them as a JSON array with this structure:
[
  {
    "title": "Job Title",
    "company": "Company Name",
    "location": "City, Country",
    "url": "https://linkedin.com/jobs/view/XXXXXXX"
  }
]
Return ONLY the JSON array, no other text. If no results, return [].
"""

EMAIL_SYSTEM = """You are an assistant that sends emails via Gmail MCP.
You will receive an HTML email body and must send it using the Gmail MCP send_email tool.
Do not modify the content — just send it as-is.
"""

# ── HTML EMAIL TEMPLATE ───────────────────────────────────────────────────────

def build_email_html(jobs: list) -> str:
    rows = ""
    for j in jobs:
        rows += f"""
        <tr>
          <td style="padding:10px;border-bottom:1px solid #eee;">{j.get('title', '—')}</td>
          <td style="padding:10px;border-bottom:1px solid #eee;">{j.get('company', '—')}</td>
          <td style="padding:10px;border-bottom:1px solid #eee;">{j.get('location', '—')}</td>
          <td style="padding:10px;border-bottom:1px solid #eee;">
            <a href="{j.get('url', '#')}" style="color:#0a66c2;text-decoration:none;">View Job</a>
          </td>
        </tr>"""

    return f"""
<html><body style="font-family:Arial,sans-serif;color:#333;max-width:800px;margin:auto;">
  <h2 style="color:#0a66c2;">LinkedIn Job Digest — {TODAY}</h2>
  <p>Senior tech roles in <strong>{LOCATION}</strong> matching your profile:</p>
  <p><em>Titles: Implementation Engineer · Onboarding Engineer · TAM · Technical Consultant · CX · Consultant</em></p>

  <table style="width:100%;border-collapse:collapse;margin-top:20px;">
    <thead>
      <tr style="background:#0a66c2;color:white;">
        <th style="padding:12px;text-align:left;">Title</th>
        <th style="padding:12px;text-align:left;">Company</th>
        <th style="padding:12px;text-align:left;">Location</th>
        <th style="padding:12px;text-align:left;">Link</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>

  <p style="margin-top:30px;font-size:12px;color:#999;">
    Found {len(jobs)} matching roles · Generated by Claude Code Job Search
  </p>
</body></html>
"""

# ── MAIN ──────────────────────────────────────────────────────────────────────

def main():
    client = anthropic.Anthropic()
    all_jobs = []
    seen_urls = set()

    print(f"Searching LinkedIn for {len(TITLES)} job titles in {LOCATION}...")

    queries = build_queries()
    for i, query in enumerate(queries, 1):
        print(f"  [{i}/{len(queries)}] {query[:80]}...")
        try:
            response = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=1000,
                system=SEARCH_SYSTEM,
                tools=[{"type": "web_search_20250305", "name": "web_search"}],
                messages=[{"role": "user", "content": f"Search for jobs using this query: {query}"}],
            )
            for block in response.content:
                if block.type == "text":
                    text = block.text.strip()
                    if text.startswith("["):
                        try:
                            jobs = json.loads(text)
                            for job in jobs:
                                url = job.get("url", "")
                                if url and url not in seen_urls:
                                    seen_urls.add(url)
                                    all_jobs.append(job)
                                    print(f"    + {job.get('title')} @ {job.get('company')}")
                        except json.JSONDecodeError:
                            pass
        except Exception as e:
            print(f"    ! Search error: {e}")

    print(f"\nTotal unique jobs found: {len(all_jobs)}")
    if not all_jobs:
        print("No jobs found.")
        return

    html_body = build_email_html(all_jobs)
    subject = f"LinkedIn Job Digest — Senior Tech Roles in {LOCATION} ({TODAY})"

    print(f"\nSending email to {RECIPIENT_EMAIL}...")
    try:
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1000,
            system=EMAIL_SYSTEM,
            mcp_servers=[{
                "type": "url",
                "url": "https://gmailmcp.googleapis.com/mcp/v1",
                "name": "gmail-mcp",
            }],
            messages=[{
                "role": "user",
                "content": (
                    f"Send an email using Gmail MCP:\n"
                    f"To: {RECIPIENT_EMAIL}\n"
                    f"Subject: {subject}\n"
                    f"Body (HTML): {html_body}\n\nUse the send_email tool now."
                ),
            }],
        )
        for block in response.content:
            if block.type == "text":
                print(f"  Response: {block.text[:200]}")
        print("Email sent!")
    except Exception as e:
        print(f"Email failed: {e}")
        with open("job_digest_preview.html", "w") as f:
            f.write(html_body)
        print("Preview saved to job_digest_preview.html")


if __name__ == "__main__":
    main()
